
Resources:

  ProxyGeneratorRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: BucketScanAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
            - s3:ListBucket
            - s3:GetObject
            - s3:PutObject
            Resource:
            - arn:aws:s3:::archivehunter-*
            - arn:aws:s3:::archivehunter-*/*
            - arn:aws:s3:::gnm-multimedia-*
            - arn:aws:s3:::gnm-multimedia-*/*
            - arn:aws:s3:::mm-archive-*
            - arn:aws:s3:::mm-archive-*/*
      - PolicyName: LogsAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
            - "logs:DescribeLogStreams"
            Resource:
            - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
      - PolicyName: ImageDownloadAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            Effect: Allow
            Action:
            - "ecr:BatchCheckLayerAvailability"
            - "ecr:BatchGetImage"
            - "ecr:GetDownloadUrlForLayer"
            - "ecr:GetAuthorizationToken"
            - ecr:GetAuthorizationToken
            Resource: "*"

  ProxyingCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Stack}-${App}-${Stage}

  ProxyingTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 5

  ProxyingTaskDefinition:
    #this is used to register the image that runs proxying tasks.  Specific commands are run via overrides.
    # See ContainerTaskManager for details.
    Type: AWS::ECS::TaskDefinition
    Properties:
      ExecutionRoleArn: !GetAtt ProxyGeneratorRole.Arn
      ContainerDefinitions:
      - Image: !Ref ProxyingTaskImageRef #specified in "resources"
        MemoryReservation: 2048 #this is the limit of memory rather than the actual amount allocated
        Name: !Sub ${Stack}-${App}Proxy-${Stage}
        LogConfiguration:
          LogDriver: awslogs
          Options:
            awslogs-group: !Ref ProxyingTaskLogGroup
            awslogs-region: !Ref AWS::Region
            awslogs-stream-prefix: ecs
      Cpu: 4096 #4 vCPU
      NetworkMode: awsvpc
      Memory: 8192  #minimum allowed with 4 vCPU
      RequiresCompatibilities:
      - FARGATE
      TaskRoleArn: !GetAtt ProxyGeneratorRole.Arn
